import fs from "fs";
import path from "path";

const rootDir = process.cwd();
const coreSchemaPath = path.join(rootDir, "src", "core", "prisma", "schema.prisma");
const extensionSchemaPath = path.join(rootDir, "src", "extensions", "prisma", "schema.prisma");
const extensionSchemaDir = path.join(rootDir, "src", "extensions", "prisma", "schema");
const outputDir = path.join(rootDir, "prisma");
const outputPath = path.join(outputDir, "schema.prisma");

const readIfExists = (filePath) => {
  if (!fs.existsSync(filePath)) return null;
  return fs.readFileSync(filePath, "utf8").trim();
};

const readExtensionFragments = () => {
  const fragments = [];
  const singleSchema = readIfExists(extensionSchemaPath);

  if (singleSchema) {
    fragments.push({
      label: path.relative(rootDir, extensionSchemaPath),
      content: singleSchema,
    });
  }

  if (fs.existsSync(extensionSchemaDir)) {
    const files = fs
      .readdirSync(extensionSchemaDir)
      .filter((fileName) => fileName.endsWith(".prisma"))
      .sort((a, b) => a.localeCompare(b));

    for (const fileName of files) {
      const filePath = path.join(extensionSchemaDir, fileName);
      const content = readIfExists(filePath);
      if (!content) continue;

      fragments.push({
        label: path.relative(rootDir, filePath),
        content,
      });
    }
  }

  return fragments;
};

const coreSchema = readIfExists(coreSchemaPath);

if (!coreSchema) {
  console.error(`Core Prisma schema not found: ${path.relative(rootDir, coreSchemaPath)}`);
  process.exit(1);
}

const extensionFragments = readExtensionFragments();
const generatedSchema = [
  "// This file is generated by scripts/sync-prisma.mjs.",
  "// Edit src/core/prisma/schema.prisma for core schema changes.",
  "// Edit src/extensions/prisma/schema/*.prisma for project-specific schema changes.",
  "",
  coreSchema,
  ...extensionFragments.flatMap((fragment) => [
    "",
    `// Extension schema: ${fragment.label}`,
    fragment.content,
  ]),
  "",
].join("\n");

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputPath, generatedSchema);

console.log(`Synced Prisma schema to ${path.relative(rootDir, outputPath)}`);
if (extensionFragments.length > 0) {
  console.log(`Included ${extensionFragments.length} extension schema fragment(s).`);
}
